version: "3.3"

networks:
  web:

services:
    openvidu:
      image: "openvidu/openvidu-server-kms:2.15.0"
      ports:
        - "4443:4443"
      environment:
        - OPENVIDU_SECRET=MY_SECRET_PASS
      networks:
            - web
    srec-video-app:
      image: "trendchaser4u/srec-video-conf:1.0.0"
      ports:
        - "80:80"
      environment:
        - SERVER_PORT=80
        - OPENVIDU_SECRET=MY_SECRET_PASS
        - OPENVIDU_URL=https://openvidu:4443
        - CALL_OPENVIDU_CERTTYPE=selfsigned
      networks:
            - web